server:
  port: 8070
spring:
  application:
    name: ${eureka.instance.appname}
eureka:
  instance:
    appname: watcher-service
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
